///////ALERT//////
export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const BEGIN = "BEGIN";
export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_STORY_BEGIN = "CREATE_STORY_BEGIN";
export const CREATE_STORY_SUCCESS = "CREATE_STORY_SUCCESS";
export const CREATE_STORY_ERROR = "CREATE_STORY_ERROR";

export const GET_MY_STORIES_SUCCESS = "GET_MY_STORIES_SUCCESS";
export const GET_MY_STORY_SUCCESS = "GET_MY_STORY_SUCCESS";

export const GET_MY_CHAPTERS_SUCCESS = "GET_MY_CHAPTERS_SUCCESS";

export const EDIT_MY_CHAPTER_SUCCESS = "EDIT_MY_CHAPTER_SUCCESS";

export const SET_EDIT_STORY = "SET_EDIT_STORY";

export const DELETE_JOB_BEGIN = "DELETE_JOB_BEGIN";

export const EDIT_STORY_BEGIN = "EDIT_STORY_BEGIN";
export const EDIT_STORY_SUCCESS = "EDIT_STORY_SUCCESS";
export const EDIT_STORY_ERROR = "EDIT_STORY_ERROR";

export const ADD_STORY_SUCCESS = "ADD_STORY_SUCCESS";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_PROFILE_CONV_SUCCESS = "GET_PROFILE_CONV_SUCCESS";
export const GET_PROFILE_ACTIVITY_SUCCESS = "GET_PROFILE_ACTIVITY_SUCCESS";

export const ADD_PROFILE_CONV_SUCCESS = "ADD_PROFILE_CONV_SUCCESS";

export const ADD_CONV_COMMENT_SUCCESS = "ADD_CONV_COMMENT_SUCCESS";

export const GET_STORIES_SUCCESS = "GET_STORIES_SUCCESS";
export const GET_ALL_STORIES_SUCCESS = "GET_ALL_STORIES_SUCCESS";
export const GET_STORY_SUCCESS = "GET_STORY_SUCCESS";
export const GET_CHAPTER_SUCCESS = "GET_CHAPTER_SUCCESS";
export const ADD_CHAPTER_CONV_SUCCESS = "ADD_CHAPTER_CONV_SUCCESS";
export const ADD_PARAGRAPH_CONV_SUCCESS = "ADD_PARAGRAPH_CONV_SUCCESS";
export const VOTE_CHAPTER_SUCCESS = "VOTE_CHAPTER_SUCCESS";
export const UNVOTE_CHAPTER_SUCCESS = "UNVOTE_CHAPTER_SUCCESS";

export const OPEN_EDIT_MODE = "OPEN_EDIT_MODE";
export const CLOSE_EDIT_MODE = "CLOSE_EDIT_MODE";

export const EDIT_PROFILE_BEGIN = "EDIT_PROFILE_BEGIN";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_ERROR = "EDIT_PROFILE_ERROR";

export const GET_PROFILE_SETTINGS = "GET_PROFILE_SETTINGS";
export const EDIT_PROFILE_SETTINGS = "EDIT_PROFILE_SETTINGS";

export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";

export const OPEN_INBOX_SUCCESS = "OPEN_INBOX_SUCCESS";
export const OPEN_MESSAGES_SUCCESS = "OPEN_MESSAGES_SUCCESS";

export const SEND_NOTIFICATION_SUCCESS = "SEND_NOTIFICATION_SUCCESS";

export const OPEN_NOTIFICATIONS_SUCCESS = "OPEN_NOTIFICATIONS_SUCCESS";

export const DELETE_NOTIFICATIONS_SUCCESS = "DELETE_NOTIFICATIONS_SUCCESS";

export const FOLLOW_PROFILE_BEGIN = "FOLLOW_PROFILE_BEGIN";
export const UNFOLLOW_PROFILE_BEGIN = "UNFOLLOW_PROFILE_BEGIN";

export const FOLLOW_PROFILE_SUCCESS = "FOLLOW_PROFILE_SUCCESS";
export const UNFOLLOW_PROFILE_SUCCESS = "UNFOLLOW_PROFILE_SUCCESS";

export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";

export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";

export const SEND_GPT_PROMPT = "SEND_GPT_PROMPT";
